controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    franka_left_robot_state_broadcaster:
      type: franka_robot_state_broadcaster/FrankaRobotStateBroadcaster
    franka_right_robot_state_broadcaster:
      type: franka_robot_state_broadcaster/FrankaRobotStateBroadcaster
    #dual_joint_impedance_example_controller:
    #  type: franka_example_controllers/DualJointImpedanceExampleController
    
franka_left_robot_state_broadcaster:
  ros__parameters:
    arm_id: left
    frequency: 30

franka_right_robot_state_broadcaster:
  ros__parameters:
    arm_id: right
    frequency: 30
    
dual_joint_impedance_example_controller:
  ros__parameters:
    arm_1:
      arm_id: left
      k_gains:
        - 24.0
        - 24.0
        - 24.0
        - 24.0
        - 10.0
        - 6.0
        - 2.0
      d_gains:
        - 2.0
        - 2.0
        - 2.0
        - 1.0
        - 1.0
        - 1.0
        - 0.5
    arm_2:
      arm_id: right
      k_gains:
        - 24.0
        - 24.0
        - 24.0
        - 24.0
        - 10.0
        - 6.0
        - 2.0
      d_gains:
        - 2.0
        - 2.0
        - 2.0
        - 1.0
        - 1.0
        - 1.0
        - 0.5
    
    